<!DOCTYPE html>
<html lang="en">
<head>
<title>Setting up my first website</title>
</head>
<body>

<h1>Human Computer Interaction - HUMCOM1 IAA2</h1>
<h2>by: Roel Liwag </h2>
<h3>BSIT </h3>
<h4>First year college </h4>
<h5>Guimba nueva ecija </h5>
<h6>January 24, 2022 </h6>
<p>This is a sample web page</p>
</body>
</html>

theme: jeykll-theme-merlot
